### ISSUE TITLE
Feature: Add multiple images to stream

### ISSUE THREAD

**Issue by ryantheleach** [univrsal/scrab#1]
Instead of deleting and replacing the source image could we get scrab to be able to keep the images on scene?

**Comment by univrsal** [comment]
I can add an option to just keep adding new sources, if that's what you mean, it'll get annoying to clean that up afterwards though

**Comment by ryantheleach** [comment]
I'd appreciate that, I usually use scrab for quickly prototyping a scene, and do it properly later.

If you feel that the clean-up is too arduous, (It's a simple click and delete) Then maybe hotkeys /buttons that delete the most recently added scrab from a list, 1 at a time? or a 'Clear all scrabs'?

Whilst I'm quite happy cleaning up afterwards, I can understand your concern.

**Comment by univrsal** [comment]
I added the option of just adding new sources, but there's no hotkey for cleaning up since there's no clean way of removing sources.
The option can be enabled by adding ``continous=true`` in the obs config file under the ``[scrab]`` section.
